### ISSUE TITLE
Tests are broken after RC update

### ISSUE THREAD

**Issue by chrisbouchard** [chrisbouchard/fate-charsheet-2.0#5]
```
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  TypeError: undefined is not an object (evaluating 'providers.forEach')
  at c:/Users/cbouchard/Documents/git/fate-charsheet-2.0/spec-bundle.js:61070
```

**Comment by asndev** [comment]
@chrisbouchard did you manage to fix this issue yet? I just ran into the same one with a project of mine.

**Comment by chrisbouchard** [comment]
@asndev I haven't done anything to address this issue since I created it, but it's still happening for me.

**Comment by chrisbouchard** [comment]
@asndev Turns out I was using `TEST_BROWSER_PLATFORM_PROVIDERS` instead of `TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS` (note the `DYNAMIC` in the name) in `spec-bundle.js`. Using the correct provider constants fixed the problem.
